In [192]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [193]:
data=pd.read_csv(r"C:\CODING\SHIASH\projects\Car price prediction\car.csv")

In [194]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner  mileage(km/ltr/kg)  engine  \
0  Individual       Manual   First Owner               23.40  1248.0   
1  Individual       Manual  Second Owner               21.14  1498.0   
2  Individual       Manual   Third Owner               17.70  1497.0   
3  Individual       Manual   First Owner               23.00  1396.0   
4  Individual       Manual   First Owner               16.10  1298.0   

  max_power  seats  
0        74    5.0  
1    103.52    5.0  
2        78    5.0  
3        90    5.0  
4      88.2    5.0

In [195]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   name                8128 non-null   object 
 1   year                8128 non-null   int64  
 2   selling_price       8128 non-null   int64  
 3   km_driven           8128 non-null   int64  
 4   fuel                8128 non-null   object 
 5   seller_type         8128 non-null   object 
 6   transmission        8128 non-null   object 
 7   owner               8128 non-null   object 
 8   mileage(km/ltr/kg)  7907 non-null   float64
 9   engine              7907 non-null   float64
 10  max_power           7913 non-null   object 
 11  seats               7907 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 762.1+ KB


In [196]:
data.isna().sum().sum()

878

In [197]:
for i in data.select_dtypes(["float64"]).columns:
    if data[i].skew()>0.5:
        data[i]=data[i].fillna(data[i].median())
    else:
        data[i]=data[i].fillna(data[i].mean())

In [198]:
data.isna().sum().sum()

215

In [199]:
data=data.dropna()

In [200]:
data.duplicated().sum()

1192

In [201]:
data=data.drop_duplicates(keep="last")

In [202]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in data:
    if data[i].dtypes=="object":
        data[i]=le.fit_transform(data[i])

In [203]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
d=scaler.fit_transform(data)
data=pd.DataFrame(d,columns=data.columns)
data

name      year  selling_price  km_driven      fuel  seller_type  \
0     0.630676  0.769231       0.042126   0.061640  0.333333          0.5   
1     0.780525  0.769231       0.034102   0.050837  0.333333          0.5   
2     0.189203  0.461538       0.012839   0.059310  1.000000          0.5   
3     0.374874  0.615385       0.019559   0.053803  0.333333          0.5   
4     0.651362  0.500000       0.010030   0.050837  1.000000          0.5   
...        ...       ...            ...        ...       ...          ...   
6716  0.370838  0.769231       0.044634   0.033891  0.333333          0.5   
6717  0.369828  0.730769       0.029087   0.046601  1.000000          0.5   
6718  0.311806  0.500000       0.010532   0.050414  0.333333          0.5   
6719  0.636731  0.576923       0.035306   0.050837  0.333333          0.5   
6720  0.824420  0.730769       0.026078   0.010591  0.333333          0.5   

      transmission  owner  mileage(km/ltr/kg)    engine  max_power  seats  
0              1.0   0.00            0.557143  0.209396   0.764890   0.25  
1              1.0   0.50            0.503333  0.293289   0.047022   0.25  
2              1.0   1.00            0.421429  0.292953   0.793103   0.25  
3              1.0   0.00            0.547619  0.259060   0.924765   0.25  
4              1.0   0.00            0.383333  0.226174   0.899687   0.25  
...            ...    ...                 ...       ...        ...    ...  
6716           1.0   0.50            0.536667  0.259060   0.909091   0.25  
6717           1.0   0.00            0.440476  0.192282   0.836991   0.25  
6718           1.0   0.25            0.400000  0.291611   0.094044   0.25  
6719           1.0   0.00            0.459524  0.209396   0.755486   0.25  
6720           1.0   0.00            0.561190  0.259060   0.727273   0.25  

[6721 rows x 12 columns]

In [204]:
x=data.drop(["selling_price"],axis=1)
y=data["selling_price"]

In [205]:
x

name      year  km_driven      fuel  seller_type  transmission  \
0     0.630676  0.769231   0.061640  0.333333          0.5           1.0   
1     0.780525  0.769231   0.050837  0.333333          0.5           1.0   
2     0.189203  0.461538   0.059310  1.000000          0.5           1.0   
3     0.374874  0.615385   0.053803  0.333333          0.5           1.0   
4     0.651362  0.500000   0.050837  1.000000          0.5           1.0   
...        ...       ...        ...       ...          ...           ...   
6716  0.370838  0.769231   0.033891  0.333333          0.5           1.0   
6717  0.369828  0.730769   0.046601  1.000000          0.5           1.0   
6718  0.311806  0.500000   0.050414  0.333333          0.5           1.0   
6719  0.636731  0.576923   0.050837  0.333333          0.5           1.0   
6720  0.824420  0.730769   0.010591  0.333333          0.5           1.0   

      owner  mileage(km/ltr/kg)    engine  max_power  seats  
0      0.00            0.557143  0.209396   0.764890   0.25  
1      0.50            0.503333  0.293289   0.047022   0.25  
2      1.00            0.421429  0.292953   0.793103   0.25  
3      0.00            0.547619  0.259060   0.924765   0.25  
4      0.00            0.383333  0.226174   0.899687   0.25  
...     ...                 ...       ...        ...    ...  
6716   0.50            0.536667  0.259060   0.909091   0.25  
6717   0.00            0.440476  0.192282   0.836991   0.25  
6718   0.25            0.400000  0.291611   0.094044   0.25  
6719   0.00            0.459524  0.209396   0.755486   0.25  
6720   0.00            0.561190  0.259060   0.727273   0.25  

[6721 rows x 11 columns]

In [206]:
y

0       0.042126
1       0.034102
2       0.012839
3       0.019559
4       0.010030
          ...   
6716    0.044634
6717    0.029087
6718    0.010532
6719    0.035306
6720    0.026078
Name: selling_price, Length: 6721, dtype: float64

In [207]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=0)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(5376, 11)
(1345, 11)
(5376,)
(1345,)


In [208]:
from sklearn.linear_model import LinearRegression
car_model=LinearRegression()
car_model.fit(x_train,y_train)

LinearRegression()

In [209]:
pred=car_model.predict(x_test)
pred

array([ 0.04248449,  0.07439296,  0.06072719, ...,  0.04568079,
        0.06576995, -0.00017949])

In [210]:
from sklearn.metrics import *
accuracy=r2_score(y_test,pred)
accuracy*100

53.9272246137248

In [211]:
from sklearn.tree import DecisionTreeRegressor
de_house_model=DecisionTreeRegressor()
de_house_model.fit(x_train,y_train)

DecisionTreeRegressor()

In [212]:
pred1=de_house_model.predict(x_test)
pred1

array([0.02507532, 0.0220663 , 0.07221674, ..., 0.06218665, 0.0451355 ,
       0.00501514])

In [213]:
accuracy1=r2_score(y_test,pred1)
accuracy1*100

89.50036633068936

In [214]:
x_train

name      year  km_driven      fuel  seller_type  transmission  \
5764  0.312311  0.576923   0.042364  0.333333          0.5           1.0   
5456  0.972755  0.692308   0.046601  0.333333          0.5           1.0   
5903  0.525227  0.884615   0.008473  1.000000          0.5           1.0   
1041  0.009586  0.653846   0.050837  0.333333          0.5           0.0   
1632  0.318870  0.923077   0.005883  1.000000          0.5           1.0   
...        ...       ...        ...       ...          ...           ...   
4931  0.542886  0.884615   0.009743  1.000000          0.5           1.0   
3264  0.521191  0.769231   0.016945  1.000000          0.5           1.0   
1653  0.318870  0.884615   0.008473  1.000000          0.5           1.0   
2607  0.028759  0.730769   0.025418  0.333333          0.5           1.0   
2732  0.477296  0.923077   0.006354  0.333333          0.5           1.0   

      owner  mileage(km/ltr/kg)    engine  max_power     seats  
5764    0.0            0.430952  0.291611   0.094044  0.250000  
5456    1.0            0.460238  0.451007   0.228840  0.250000  
5903    0.0            0.588095  0.057718   0.570533  0.250000  
1041    0.0            0.304762  0.451007   0.338558  0.250000  
1632    0.0            0.404762  0.324497   0.159875  0.250000  
...     ...                 ...       ...        ...       ...  
4931    0.0            0.509524  0.192282   0.846395  0.250000  
3264    0.5            0.541429  0.057718   0.570533  0.250000  
1653    0.0            0.404762  0.324497   0.159875  0.250000  
2607    0.5            0.605714  0.104698   0.614420  0.250000  
2732    0.5            0.394048  0.628859   0.065831  0.333333  

[5376 rows x 11 columns]

In [215]:
y_train

5764    0.034604
5456    0.039117
5903    0.030090
1041    0.127382
1632    0.092277
          ...   
4931    0.048646
3264    0.022066
1653    0.087262
2607    0.017051
2732    0.082247
Name: selling_price, Length: 5376, dtype: float64

Decision Tree Prediction

In [216]:
de_house_model.predict([[0.312311	,0.576923	,0.042364,	0.333333	,0.5	,1.0,	0.0	,0.430952,	0.291611,	0.094044,	0.250000]])

C:\Users\sundh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([0.03460391])

Linear Prediction

In [217]:
car_model.predict([[0.312311	,0.576923	,0.042364,	0.333333	,0.5	,1.0,	0.0	,0.430952,	0.291611,	0.094044,	0.250000]])

C:\Users\sundh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.03602364])

In [218]:
de_house_model.predict([[0.972755,	0.692308	,0.046601,	0.333333,	0.5,	1.0,	1.0	,0.460238,	0.451007	,0.228840,	0.250000]])

C:\Users\sundh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([0.03911745])